"""empty message

Revision ID: 28835f2df6e5
Revises: 7ba071071bb3
Create Date: 2020-01-18 22:10:25.697455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28835f2df6e5'
down_revision = '7ba071071bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
